from fastapi import APIRouter

from app.api.v1 import ai, auth, backoffice, backoffice_auth, billing, catalog, checkout, combos, customers, dashboard, ecartpay, employees, inventory, kiosk, kiosk_promotions, kiosk_settings, kioskos, modifiers, orders, organizations, platform_orders, pricing, reports, restaurant, returns, roles, sales, stores, subscriptions, suppliers, supplies, sync, users, variants, warehouse, webhooks

api_router = APIRouter()

api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(roles.router)
api_router.include_router(stores.router)
api_router.include_router(catalog.router)
api_router.include_router(variants.router)
api_router.include_router(supplies.router)
api_router.include_router(combos.router)
api_router.include_router(modifiers.router)
api_router.include_router(orders.router)
api_router.include_router(sales.router)
api_router.include_router(returns.router)
api_router.include_router(checkout.router)
api_router.include_router(customers.router)
api_router.include_router(employees.router)
api_router.include_router(kiosk.router)
api_router.include_router(kiosk_promotions.router)
api_router.include_router(kiosk_settings.router)
api_router.include_router(kioskos.router)
api_router.include_router(sync.router)
api_router.include_router(restaurant.router)
api_router.include_router(organizations.router)
api_router.include_router(platform_orders.router)
api_router.include_router(reports.router)
api_router.include_router(ai.router)
api_router.include_router(dashboard.router)
api_router.include_router(inventory.router)
api_router.include_router(pricing.router)
api_router.include_router(suppliers.router)
api_router.include_router(warehouse.router)
api_router.include_router(subscriptions.router)
api_router.include_router(billing.router)
api_router.include_router(ecartpay.router)
api_router.include_router(webhooks.router)
api_router.include_router(backoffice_auth.router)
api_router.include_router(backoffice.router)
